apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: thiagorc/meubanco:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3306

      volumeMounts:
        - name: local
          mountPath: /var/lib/mysql
      volumes:
        - name: local
          persistentVolumeClaim:
            claimName: local
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-connect-db
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
